owner: SkwalExe
repo: uptime.skwal.net
user-agent: "Skwal Status Page"
sites:
  - name: Google
    url: https://www.google.com
  - name: Skwal
    url: https://skwal.net
assignees:
  - SkwalExe

status-website:
  cname: uptime.skwal.net
  logoUrl: https://skwal.net/img/banner.png
  name: Upptime
  introTitle: "SkwalNet services uptime monitor and status page."
  introMessage: "Administrator: Léopold Koprivnik <koprivnik@skwal.net>"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
    - title: Website
      href: https://skwal.net
  i18n:
    footer: "**Subscribe to real-time updates:** Visit our [GitHub repository](https://github.com/SkwalExe/uptime.skwal.net) and click on the _Notifications_ dropdown and select _All Activity_."
